# This is a basic workflow to help you get started with Actions

name: Semantic Release

# El flujo de control se va a disparar cuando
on:
  # se haga un push o un pull request
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Esto lo dejamos github actions corre en una version de ubuntu
    runs-on: ubuntu-latest

    # Steps con cada uno de los pasos que queremos ejecutar
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false # <--- this
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.13.0

      - name: Install Dependencies
        run: npm install

      - name: Build App
        run: npm run build
      # Despues del build vamos a ejecutar el semantic release
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
